import {
  Beef,
  Beer,
  Book,
  Briefcase,
  Bus,
  Car,
  Carrot,
  CircleDashed,
  Coffee,
  CreditCard,
  Dumbbell,
  FileText,
  Film,
  Fish,
  Fuel,
  Gamepad2,
  Gift,
  Heart,
  Hotel,
  House,
  Landmark,
  Luggage,
  Map,
  Milk,
  Music,
  PawPrint,
  Pill,
  PiggyBank,
  Pizza,
  Plane,
  Receipt,
  Salad,
  Sandwich,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Stethoscope,
  Tent,
  TrainFront,
  TreePalm,
  Utensils,
  Wine,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';

import type { CategoryIconName } from '@/utils/categoryStyle';

/** The server's CategoryIcon enum, rendered with the same Lucide set it names. */
export const CATEGORY_ICON_MAP: Record<CategoryIconName, LucideIcon> = {
  utensils: Utensils,
  car: Car,
  receipt: Receipt,
  'shopping-bag': ShoppingBag,
  'circle-dashed': CircleDashed,
  house: House,
  coffee: Coffee,
  plane: Plane,
  gift: Gift,
  heart: Heart,
  book: Book,
  dumbbell: Dumbbell,
  smartphone: Smartphone,
  zap: Zap,
  'piggy-bank': PiggyBank,
  fuel: Fuel,
  'shopping-cart': ShoppingCart,
  pill: Pill,
  stethoscope: Stethoscope,
  'file-text': FileText,
  film: Film,
  music: Music,
  'gamepad-2': Gamepad2,
  'paw-print': PawPrint,
  bus: Bus,
  'train-front': TrainFront,
  hotel: Hotel,
  briefcase: Briefcase,
  landmark: Landmark,
  'credit-card': CreditCard,
  carrot: Carrot,
  salad: Salad,
  beef: Beef,
  fish: Fish,
  pizza: Pizza,
  sandwich: Sandwich,
  milk: Milk,
  beer: Beer,
  wine: Wine,
  luggage: Luggage,
  map: Map,
  tent: Tent,
  'tree-palm': TreePalm,
  ship: Ship,
};

/** Unknown values fall back rather than crash, so a new server-side icon cannot break old builds. */
export function categoryIcon(name: string | null | undefined): LucideIcon {
  return CATEGORY_ICON_MAP[(name ?? '') as CategoryIconName] ?? CircleDashed;
}
